# action.yml
name: 'DD2482: MetaCA'
description: 'Auto verify mandatory parts of course automation'
inputs:
  deadline:
    description: 'deadline for first task'
    required: true
  event_path:
    description: 'github.event_path'
    required: true
  secret:
    description: 'github.secrets'
    required: true


runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_DEADLINE: ${{ inputs.deadline }}
    INPUT_EVENT_PATH: ${{ inputs.event_path }}
    INPUT_SECRET: ${{ inputs.secret }}
