name: "Mandatory part(s): course-automation"

on:
  pull_request:
    paths:
      - 'contributions/course-automation/*/*.md'

env:
  DEADLINE: "2022-04-05T17:00:00Z"

jobs:
  check-pull-request:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: 'Parsing markdown for mandatory part(s)'
      uses: 'landeholt/dd2482-course-automation/action.yml'
      with:
        deadline: ${{ env.DEADLINE }}
